#!/usr/bin/env just --justfile

@default:
    just -f {{ justfile() }} --list --no-aliases

check:
    ruff check *.py
    ruff format --check *.py
    just -f {{ justfile() }} --unstable --fmt --check

fmt:
    ruff format *.py
    just -f {{ justfile() }} --unstable --fmt

test:
    pytest

sync:
    pip-sync requirements.txt requirements-dev.txt

update:
    pip-compile --strip-extras --upgrade requirements.in --output-file requirements.txt
    pip-compile --strip-extras --upgrade requirements-dev.in --output-file requirements-dev.txt

update-and-sync: update sync
